AWSTemplateFormatVersion: "2010-09-09"
Description: "Coffee Delivery Service Infrastructure"
Parameters:
  ResourcesBucket:
    Type: String
    Description: "The S3 bucket where Lambda function code zips and API Gateway YAML exist"
    AllowedPattern: ^[-a-z0-9]+$
    Default: "bjp2158-deploy-resources"
    ConstraintDescription: "Malformed input - Parameter must only use lowercase letters, numbers, and dashes"
  FrontendStackS3Key:
    Type: String
    Description: "The S3 object key for the frontend stack YAML file"
    Default: "coffee-delivery/frontend-template.yaml"
  AppBucketBaseName:
    Type: String
    Description: "The base name for the S3 bucket that serves the app UI"
    AllowedPattern: ^[-a-z0-9]+$
    Default: "coffee-delivery-service-app"
    ConstraintDescription: "Malformed input - Parameter must only use lowercase letters, numbers, and dashes"
  BackendStackS3Key:
    Type: String
    Description: "The S3 object key for the backend stack YAML file"
    Default: "coffee-delivery/backend-template.yaml"
  FunctionS3ObjectKeySuffix:
    Type: String
    Description: "The suffix on S3 object keys for Lambda functions"
  ApiStackS3Key:
    Type: String
    Description: "The S3 object key for the API stack YAML file"
    Default: "coffee-delivery/api-template.yaml"
  PhotosBucketBaseName:
    Type: String
    Description: "The base name of the S3 bucket where image resources should be stored"
    Default: "coffee-delivery-photos"
  ApiGatewayYamlS3ObjectKey:
    Type: String
    Description: "The S3 object key for the API Gateway YAML file"
    Default: "coffee-delivery/api-swagger.yaml"
  StageName:
    Type: String
    Description: "The name to use for the deployed API stage"
    Default: "v1"
  AdminUserEmail:
    Type: String
    Description: "The email to use for the administrator API key"

Resources:
  # Bucket for photos
  S3PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Ref PhotosBucketBaseName
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  S3PhotosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3PhotosBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3PhotosBucket}/*"

  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ResourcesBucket}/${FrontendStackS3Key}"
      Parameters:
        ResourcesBucket: !Ref ResourcesBucket
        AppBucketBaseName: !Ref AppBucketBaseName
        ResourceSuffix: !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"

  BackendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: FrontendStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ResourcesBucket}/${BackendStackS3Key}"
      Parameters:
        ResourcesBucket: !Ref ResourcesBucket
        FunctionS3ObjectKeySuffix: !Ref FunctionS3ObjectKeySuffix
        FrontEndUrl: !GetAtt FrontendStack.Outputs.WebsiteUrl
        ResourceSuffix: !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"

  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: BackendStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ResourcesBucket}/${ApiStackS3Key}"
      Parameters:
        PhotosBucket: !Ref S3PhotosBucket
        ResourcesBucket: !Ref ResourcesBucket
        ApiGatewayYamlS3ObjectKey: !Ref ApiGatewayYamlS3ObjectKey
        LambdaExecutionRoleName: !GetAtt BackendStack.Outputs.LambdaExecutionRoleName
        StageName: !Ref StageName
        AdminUserEmail: !Ref AdminUserEmail
        ResourceSuffix: !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"

Outputs:
  # Base Resources
  S3PhotosBucket:
    Description: "Bucket for photos"
    Value: !Ref S3PhotosBucket

  # Child Stacks
  FrontendStackId:
    Description: "ID of backend stack"
    Value: !Ref FrontendStack
  BackendStackId:
    Description: "ID of backend stack"
    Value: !Ref BackendStack
  ApiStackId:
    Description: "ID of API stack"
    Value: !Ref ApiStack
